### ISSUE TITLE
Cannot deploy on Cloudflare Pages or Vercel Edge Functions

### ISSUE THREAD

**Issue by flayks** [swellstores/swell-node#13]
I'm trying to deploy a site using the swell-node library which is based on a custom API endpoint `/api/swell` (mostly to avoid exposing the tokens and have more control) on Cloudflare Pages or Vercel Edge Functions but I get these errors:

```
21:12:56.149 | > Using @sveltejs/adapter-cloudflare
-- | --
21:12:56.243 | ✘ [ERROR] Could not resolve "events"
21:12:56.243 |  
21:12:56.244 | node_modules/swell-node/lib/client.js:1:29:
21:12:56.244 | 1 │ const EventEmitter = require('events');
21:12:56.244 | ╵                              ~~~~~~~~
21:12:56.244 |  
21:12:56.245 | The package "events" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
21:12:56.245 |  
21:12:56.245 | ✘ [ERROR] Could not resolve "crypto"
21:12:56.246 |  
21:12:56.246 | node_modules/swell-node/lib/client.js:2:23:
21:12:56.246 | 2 │ const crypto = require('crypto');
21:12:56.247 | ╵                        ~~~~~~~~
21:12:56.249 |  
21:12:56.249 | The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

Do you think there would be a way to make it work on these platforms? Or is it _too_ relying on node?

**Comment by logeshswell** [comment]
@flayks I doubt that Cloudflare Pages can host only static content and it will not run a web server such as Express, etc.
swell-node should be used in the backend client (or in webserver hosting) and not in frontend apps.

I believe the following guides would help you deploy it in Vercel.
https://vercel.com/guides/handling-node-request-body
https://vercel.com/docs/concepts/functions/serverless-functions

Hope this answers your question. If not, please reply to this thread and I am happy to answer you.
