### ISSUE TITLE
[Bug] Methods don't retrieve information

### ISSUE THREAD

**Issue by kevinccbsg** [swellstores/swell-node#2]
I was using this library v3.1.4 and v3.1.3 and in both versions, in macOS, and in our Live environment (Docker image node:10.4) we have this problem.

When we do a request to the API it gets stuck and does not retrieve any information.

```js
const result = await swell.get('/accounts', { where: { email } })
// no response
```
If we do the same but using Axios we get the results.

```js
const { data: result } = await axios.get(`https://api.swell.store/accounts?where[email]=${email}`, {
      auth: {
        username: 'username',
        password: 'password',
      },
    });
```

We've been using this package since 2019 and we haven't had this problem.

You can reproduce the error with this code:

```js
const swell = require('swell-node');

swell.init('my-store', 'secret-key');

const searchAccount = async email => {
  console.log('email', email);
  const result = await swell.get('/accounts', { where: { email } })
  console.log('searchAccount', result);
  return result;
};

searchAccount('test@test.com');
```

Execution result `node app.js`

<img width="230" alt="Screen Shot 2020-07-24 at 14 26 57" src="https://user-images.githubusercontent.com/12685053/88391109-cb334480-cdb9-11ea-9c85-de77b13fe7db.png">

**Comment by ericingram** [comment]
@kevinccbsg thanks for the report, we've confirmed the issue and are working on a fix.

It appears to be caused by some part of the SSL chain, but as a workaround you can point to the backup domain:

```
swell.init('my-store', 'secret-key', { host: 'api.schema.io' });
```

**Comment by ericingram** [comment]
@kevinccbsg this has been fixed. The actual cause was that one of our proxy servers wasn't deployed correctly and only affected the TCP protocol for the api.swell.store domain.

Sorry for the trouble 🤞

**Comment by kevinccbsg** [comment]
Thanks, @ericingram! Should I change the workaround? Or is this going to work too?

```
swell.init('my-store', 'secret-key', { host: 'api.schema.io' });
```

Because I could not do it and if it is necessary I'll try to do it as soon as possible if not I can wait for next week.

**Comment by ericingram** [comment]
@kevinccbsg both domains will continue to work in perpetuity, so you don't have to change it if you prefer not to tinker
