### ISSUE TITLE
Unable to use Swell-node

### ISSUE THREAD

**Issue by Daniel-Alamezie** [swellstores/swell-node#25]
Hi, 
I am hoping this is a mistake on my part and am doing something wrong, but i recently started trying out swell , and since i started i have been having big issues and problems trying to using the backend 'swell-node'.

I have followed the documentations closely to have the package installed in my project, but when i try using it in my project it doesnt seem to find the module.

![image](https://github.com/swellstores/swell-node/assets/74880857/027d3868-18ec-4dcc-8ba7-a24156a6873d)

![image](https://github.com/swellstores/swell-node/assets/74880857/6366c243-c5cb-46eb-bd58-a210fde0ead9)

Note:
 - I am using a Next 13 project.

**Comment by Daniel-Alamezie** [comment]
Hi, I am using app directory with next 13.

In the root directory I have my Utica folder with a folder for swell, in which I have a swellnode function should connect to swell-node backend but when I try to use this it’s never connected or let me use swell-node. I use the client api for swell just fine but not the back end. I can try provide step by step screenshot of my code base and the result to show you

**Comment by ericingram** [comment]
I would guess the next 13 app directory code is run in a serverless function that doesn't have `tls`, but you can use a simple HTTP client instead

**Comment by sags95** [comment]
@Daniel-Alamezie actually it seems that this occurs when you're invoking swell-node in a client component, as swell-node is a nodejs module you would have to use it in a server component.

**Comment by Daniel-Alamezie** [comment]
@sags95 ahh so you’re saying fetch the data in a server component first then render in on the client?

**Comment by sags95** [comment]
Yes that's correct, or you could write a Route Handler to call the Backend API and call this from your client component.

**Comment by Daniel-Alamezie** [comment]
Hi @sags95 i  have tried this approach but it does not seem to make a difference.
I have followed the approach of trying to render it in the server and that doesnt seem to make any difference. it doesnt recognize the module.
Is there something i am doing wrong?
![image](https://github.com/swellstores/swell-node/assets/74880857/d1945945-cdd8-4703-8570-737b7743e5b8)
![image](https://github.com/swellstores/swell-node/assets/74880857/7eb65b9b-8a47-4af4-b4af-472dceb3e24a)

**Comment by Daniel-Alamezie** [comment]
p.s node is installed, realized that the message might be abit misleading,
![image](https://github.com/swellstores/swell-node/assets/74880857/6c583293-b10c-448d-98de-d72d336a967f)
it just cant find the swell-node module even tho it is installed

**Comment by sags95** [comment]
Can you try cloning this repo and testing? https://github.com/sags95/swell-node-test

Also just a typo I noticed in the `getData` method, the endpoint would be `/products` instead of `/product`

**Comment by Daniel-Alamezie** [comment]
let me give it ago, thanks

**Comment by Daniel-Alamezie** [comment]
hmm strange, it works

**Comment by Daniel-Alamezie** [comment]
the only difference i see between both projects are cos one of them is a tsx project and the other is a Js project. could that be a factor?

**Comment by sags95** [comment]
> the only difference i see between both projects are cos one of them is a tsx project and the other is a Js project. could that be a factor?

I just tested it in a new next tsx project and still not seeing an issue unfortunately. There could be some misconfiguration with npm or node. Are you seeing this issue in new next projects?

**Comment by Daniel-Alamezie** [comment]
lemme try making a new tsx project

**Comment by Daniel-Alamezie** [comment]
@sags95 ahh getting the same error on a new tsx project.
Steps to replicate.
-----------------------------
1. ran the create next app command.
![image](https://github.com/swellstores/swell-node/assets/74880857/508c7dc8-cb45-40dd-88d6-a52fbec4c231)

2. installed swell-node
![image](https://github.com/swellstores/swell-node/assets/74880857/7f9d71a9-8844-493c-b175-3ca6cc454ef5)

3. added the method on the page.
![image](https://github.com/swellstores/swell-node/assets/74880857/288cfcea-e4da-454a-af8a-6a43a2ccac2c)

4. added necessary env variables 
and got the error i was getting
![image](https://github.com/swellstores/swell-node/assets/74880857/9e6d2795-f2f3-420f-b549-e196ac9345f3)

**Comment by Daniel-Alamezie** [comment]
Tried making a new js project following the exact steps and it works fine, i think it might be the tsx project

**Comment by Daniel-Alamezie** [comment]
@sags95  i think i fixed the issue with it

**Comment by sags95** [comment]
Glad to hear that @Daniel-Alamezie! In the meantime I'll close this issue. If you're still having issues feel free to create a new discussion.
