### ISSUE TITLE
Add example for createClient 

### ISSUE THREAD

**Issue by neodmy** [swellstores/swell-node#3]
Hi there. 

I've been checking the official documentation, and AFAIK, there is no mention of the possibility you offer to create more than one client (`createClient` vs just `init` the exposed client instance). This may be quite useful for people having to interact with more than one store on the same service.

As the documentation in this repo is still in progress, maybe adding a simple reference in the **Connect** section like the following could be enough to keep rolling:

```js
const swell = require('swell-node');

// Exposes a client instance
swell.init('my-store', 'secret-key');

// Creates client intances to interact with several stores
const myClient1 = swell.createClient().init('my-store-1', 'secret-key-1');
const myClient2 = swell.createClient().init('my-store-2', 'secret-key-2');
```

Greetings 👋

**Comment by ericingram** [comment]
@neodmy 👋 

Appreciate you calling that out. It's really common to use that approach for migration scripts and the like. I added an example to the readme along those lines.
