### ISSUE TITLE
Carts Not Getting Created

### ISSUE THREAD

**Issue by ElBarbs** [swellstores/swell-node#32]
Hi.

I'm using `swellNode.post("/carts")` to create a new empty cart before adding items.

It was working fine before, but now there's no cart being created when I go in the Swell Dashboard.

Anyone with the same issue?

**Comment by ericingram** [comment]
I'm not seeing this happen in a test store, can you make sure you're looking at the right environment in the dashboard?

**Comment by ElBarbs** [comment]
> I'm not seeing this happen in a test store, can you make sure you're looking at the right environment in the dashboard?

Yeah, I'm in the right environment.
Go under Developer > Console and try to POST a new cart. It won't appear in the list (at least on my end).

**Comment by ericingram** [comment]
The carts page in the dashboard typically only shows those with at least 1 item

**Comment by ElBarbs** [comment]
> The carts page in the dashboard typically only shows those with at least 1 item

Thank you for the information, I didn't know that!

Looking back at my code, I realised that the issue was the `status` field returned by the new cart.

After creating the cart, I was retrieving it using this query:
`await swellNode.get("/carts/{id}", {
          id: cartID,
          where: {
            status: {
              $in: ["active", "recovered"],
            },
          },
        })`

The issue was that the `status` field was not set to "active", but to some kind of ID. I don't know if it's an error and they changed the status codes.
